### ISSUE TITLE
How to change the settings for xiao esp32s3 sense

### ISSUE THREAD

**Issue by mqgw** [78/xiaozhi-esp32#2]
Recently I tried to reuse the code for xiao esp32s3 sense. Have tried to change the GPIO as below, but failed to wake  the chips. Besides these changes, what else needs the change?

    chan_cfg.id = I2S_NUM_1;
    ESP_ERROR_CHECK(i2s_new_channel(&chan_cfg, nullptr, &rx_handle_));
    std_cfg.clk_cfg.sample_rate_hz = (uint32_t)input_sample_rate_;
    std_cfg.gpio_cfg.bclk = (gpio_num_t)42; //CONFIG_AUDIO_DEVICE_I2S_MIC_GPIO_BCLK;
    std_cfg.gpio_cfg.ws = I2S_GPIO_UNUSED;//(gpio_num_t)CONFIG_AUDIO_DEVICE_I2S_MIC_GPIO_WS;
    std_cfg.gpio_cfg.dout = I2S_GPIO_UNUSED;
    std_cfg.gpio_cfg.din = (gpio_num_t)41; //CONFIG_AUDIO_DEVICE_I2S_GPIO_DIN;

**Comment by 78** [comment]
What do you mean by "wake the chips"?
I am not very familiar with I2S either. I have only been working with it for a month. But as far as I know, the WS pin needs to be set. If you are also using INMP441.
XIAO esp32s3 has too few GPIO pins. You should use duplex mode to share the BCLK and WS pins if you have a speaker and a microphone both connected.

**Comment by mqgw** [comment]
Thanks. After several tests, the issue can be solved by changing I2S from std to pdm.

**Comment by 78** [comment]
I have done it with one I2S.

![IMG_1565](https://github.com/user-attachments/assets/0811e3e1-e519-4fad-a47e-c0e3efd3aa72)

**Comment by JosenJin** [comment]
> Thanks. After several tests, the issue can be solved by changing I2S from std to pdm.

hi friend, I also use xiao esp32 sense, can you share the code? Is your camera integrated?
