### ISSUE TITLE
最新的0.3和0.31 bin文件烧录后喇叭全是噪音

### ISSUE THREAD

**Issue by grswxt** [78/xiaozhi-esp32#4]
将最新的0.3.0和0.3.1的bin文件烧录到esp32s3 wroom N16R8开发板后，烧录过程正常，烧录完毕，将usb线连接到usb接口，WiFi配网完成后，喇叭立刻就是噪音，将0.2.2的bin文件重新烧录，WiFi配网后，是正常的。显然最新版都是有问题的。请解决一下。

**Comment by 78** [comment]
最新版本采用的是新版的接线方式，要按照新版本重新接线。

查看百科：https://ccnphfhqs21z.feishu.cn/wiki/EH6wwrgvNiU7aykr7HgclP09nCh
