### ISSUE TITLE
喇叭没有声音

### ISSUE THREAD

**Issue by caseylai** [78/xiaozhi-esp32#6]
首先感谢作者开源代码及写了非常详实的文档，对于新入门的小白来说，节省了很多复刻时间：）

目前程序编译运行都没有问题，非常顺利。在控制面板注册后已经可以看到串口正常打印输出对话内容，但目前的问题是喇叭没有输出声音，非常奇怪。已经把功放的线拔过了重插（确认连线无问题），杜邦线换了一遍，在面包板上也换了位置，喇叭和功放的连接处也重新拧紧了螺丝，应该没有问题。

请问下这种情况应该如何排查问题，第一次用单片机…… 问题肯定是在硬件上，有什么方便的办法可以测试下是否是喇叭、功放或者是连线的问题吗？

**Comment by caseylai** [comment]
还没有，重新买了一套喇叭、功放、线、面包板，打算排除法试下。

咱们有微信群吗？QQ好多年都不用了

**Comment by 78** [comment]
我也是因为接触硬件才重新用起QQ的

**Comment by caseylai** [comment]
问题解决了，买了新的功放和喇叭，替换了就好了。也不太清楚到底是哪里的问题，家里也没有设备… 是不是该准备个示波器什么的…
