### ISSUE TITLE
mbedtls_ssl_handshake returned -0x7200

### ISSUE THREAD

**Issue by LY649384041** [78/xiaozhi-esp32#7]
您好，我在尝试自建websocket检测小智发来的信息，但是修改Websocket URL为ws://192.168.31.99:8090/或wss://192.168.31.99:8090/ 同时sdk设置不进行任何的证书认证也不行，我比较小白，还请不要生气，可以给写思路点拨吗，非常感谢您的解答。
I (15993) WebSocket: Connecting to ws://192.168.31.99:8090/
E (16163) esp-tls-mbedtls: mbedtls_ssl_handshake returned -0x7200
I (16163) esp-tls-mbedtls: Certificate verified.
E (16163) esp-tls: Failed to open new connection
E (16173) TlsTransport: Failed to connect to 192.168.31.99:8090
E (16173) WebSocket: Failed to connect to server
E (16183) Application: Failed to connect to websocket server
I (16193) Application: STATE: idle

I (5794) WebSocket: Connecting to wss://192.168.31.99:8090/
E (6034) esp-tls-mbedtls: mbedtls_ssl_handshake returned -0x7200
E (6034) esp-tls: Failed to open new connection
E (6034) TlsTransport: Failed to connect to 192.168.31.99:8090
E (6034) WebSocket: Failed to connect to server
E (6044) Application: Failed to connect to websocket server
I (6054) Application: STATE: idle

**Comment by 78** [comment]
最新的代码支持非SSL的连接了，可以更新到最新代码再试试。
