### ISSUE TITLE
请求支持esp32s3box3

### ISSUE THREAD

**Issue by jli113** [78/xiaozhi-esp32#8]
请求支持esp32s3box3

**Comment by 78** [comment]
这个东西卖得好贵！！最近有空的话我看看

**Comment by 78** [comment]
已支持box3使用的es8311和es7210，需要自行配置GPIO进行适配。

**Comment by jli113** [comment]
![388db85364336d80754b7c53f9c507b](https://github.com/user-attachments/assets/7d0ab3da-a69f-4f2d-aff9-bc0e9281acd4)
这个要怎么配置gpio?

**Comment by 78** [comment]
已经有群友试验成功，可以在群里交流

**Comment by 78** [comment]
最新版本已经可以选择esp-box-3的预设配置。

**Comment by wild-civil** [comment]
既然已经支持esp32-s3-box3，(≧∇≦)ﾉ请求兼容esp32-s3-box
