### ISSUE TITLE
单独编译一个esp32c3的duplex固件？

### ISSUE THREAD

**Issue by jumbo5566** [78/xiaozhi-esp32#9]
能否单独编译一个esp32c3的duplex固件？现在带屏的c3开发板小巧好用

**Comment by jumbo5566** [comment]
编译失败 esp_afe_sr_models.h: No such file or directory
C3没有esp-sr这个库

**Comment by 78** [comment]
配置的时候，在Xiaozhi Assitant栏目下把esp afe的勾选去掉
